#=========================================================================
# TravisCI Setup
#=========================================================================

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

language: python, cpp
python:
    - 3.6

dist: bionic

sudo: require

env:
    - CONFIG=""

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - g++-8

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:
    # Install Python requirements
    - pip install --upgrade pip setuptools twine
    - pip install numpy pyyaml mkl mkl-include setuptools cmake cffi typing sklearn tqdm pytest
    - pip list

#------------------------------------------------------------------------
# Build and run pytorch tests with emulation layer
#------------------------------------------------------------------------

script:
    - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
    - export CC=/usr/bin/gcc-8
    - export CXX=/usr/bin/g++-8
    - export CFLAGS="-D_XOPEN_SOURCE=500 -D_BSD_SOURCE"
    - ldd --version
    - gcc --version
    - source setup_emul_build_env.sh
    - python setup.py install
    - pip list
    - cd hammerblade/torch/tests
    - python -m pytest -v .
