#=========================================================================
# TravisCI Setup
#=========================================================================

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

language: python, cpp
python:
    - 3.6

dist: bionic

env:
    - CONFIG=""

compiler:
    - gcc

addons:
    apt:
        packages:
            - gcc-8
            - g++-8

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:
    # Install Python requirements
    - pip install --upgrade pip setuptools twine
    - pip install numpy pyyaml mkl mkl-include setuptools cmake cffi typing sklearn tqdm pytest
    - pip list

#------------------------------------------------------------------------
# Build and run pytorch tests with emulation layer
#------------------------------------------------------------------------

script:
    - source setup_emul_build_env.sh
    - python setup.py install
    - pip list
    - cd hammerblade/torch/tests
    - python -m pytest -v .
